### ISSUE TITLE
Use the googletest library for testing

### ISSUE THREAD

**Issue by holke** [holke/t8code#14]
[Google Test](https://github.com/google/googletest) is a great framework for unit testing and we want to integrate it into our own testing workflow.

**Comment by holke** [comment]
I already started integrating Google Test on the feature-googletest branch.
There remain a few things to do:
   - Use the MPI compatible version of Google Test. This version is currently not public, but i will make it public soon and then it should be integrated in `t8code`
   - Have `make check` create the correct output: It should print out the Google Test output printing for each test whether it failed or not, instead of only a singe line saying that the overall Test suite was succesfull or not.
   - Rewrite the currently existing tests in Google Test
   - Implement more tests

**Comment by holke** [comment]
Some progress here:

David made a new Make target `gtest` that successfully parses the gtest output.

I configured the test/Makefile such that (if we eventually  use Googletest MPI) the test library is compiled with MPI support only if t8code is configured with MPI support.

**Comment by holke** [comment]
I noticed a flaw in the gtest make target:
Its structure is
```
make check
# Some grep magic to get the output of Googletest
```
It captures the Googletest output, but only if all tests suceed.
If a test fails, then the `make check` line fails and hence the target does not continue with the grepping of the results,
thus the purpose (i.e. notifying the user which tests fails).
We can prevent the target from stopping by writing `-make check`, ignoring the return value of `make check`.

However, this way we also do not catch compiler errors...

**Comment by Davknapp** [comment]
The compile errors are shown in the output in the  make:test/test_..... section. You would rather have a section in gtest output at the and with some kine of count of all compiler errors?

**Comment by holke** [comment]
The gtests should not be performed at all when `make check` has compiler errors.
But they should be performed when `make check` compiles well but some tests fail.

**Comment by holke** [comment]
In a discussion with David, we had the idea that we could try to put all the gtest result grepping into a script and adding this script in test/Makefile.am as a test case.
This way we could also get rid of the gtest target.
The script (shell/python/c) should be plattform independent, though. (and maybe not python since it would add an additional dependency on the python interpreter to t8code).

**Comment by holke** [comment]
@lukasdreyer @Davknapp can we close this issue?
we are, after all, using googletest now.

**Comment by Davknapp** [comment]
> @lukasdreyer @Davknapp can we close this issue? we are, after all, using googletest now.

In my opinion, we can close it

**Comment by lukasdreyer** [comment]
In my opinion, we can close it as well
