### ISSUE TITLE
A few suggestions regarding the installation

### ISSUE THREAD

**Issue by jackerschott** [holke/t8code#152]
I have a few notes and suggestions regarding the installation of t8code on linux, as a few directories and files get installed into somewhat odd locations. The following is with `--prefix=/usr` in mind.

First the t8code headers (excluding the p4est and libsc ones) files get not installed into `/usr/include`, but rather into `/usr/include/src`, which is probably not intended, unnecessary and likely confusing for the end user. Note than one would have to either define `/usr/include/src` as an additional include directory or include t8code files as i.e. `#include <src/t8.h>`.
The source of this problem is that the header files are contained within the `src` subdirectory and are installed with the `nobase_` prefix. The easiest fix here would be to just remove this prefix, however that would also remove the `t8_forest`, `t8_cmesh`, `t8_data`, etc. subdirectories. Another way would be to define extra include directories for each of these subfolders.

Second there are `data` and `ini` directories which are installed directly into `/usr/share/`. As far as i know these directories are not considered standard (correct me if I am mistaken here) and therefore clutter `/usr/share` a bit. I would suggest putting these into `/usr/share/libsc/data`, `/usr/share/p4est/data`, `/usr/share/t8code/data` and `/usr/share/libsc/ini`.

Third you install `ax_prefix_config_h.m4`, `ax_split_version.m4` into `/usr/share/aclocal`, which are not t8code, p4est or libsc specific files but belong to GNU autoconf-archive. Therefore they raise conflicts with the respective package on probably most linux distributions (at least on Archlinux and Debian). This could be fixed by simply not installing these files and mention autoconf-archive as a dependency of t8code.

Fourth you install `Makefile.t8.mk`, `Makefile.p4est.mk`, `Makefile.sc.mk` directly into `/usr/etc` (or `/etc` on a FHS compliant system) which also clutters `/etc` similiar to the second point. The solution here could be the same: One could install these files into `/etc/t8code`, `/etc/p4est` and `/etc/libsc` subdirectories.

And last but not least, you could maybe consider mentioning libsc and p4est as dependencies rather than installing them through git submodules. I know that this is more of a conceptual problem than a practical one and it would probably render the installation of t8code by source a little bit more difficult. The last point could be maybe avoided though by making this optional. I mention this point because imagine it opposes the concept by which programs are packaged on probably any linux distribution.

I am aware that many points would have to be considered for libsc and p4est and not only for t8code, so I could open an Issue there as well. Also I already made patches for myself in libsc, p4est and t8code that address points 1-4, so I would be happy to open a pull request regarding any of those.

**Comment by jackerschott** [comment]
Thank you, no problem.

#153, #154 and #155 should fix my points 1,2 and 4, at least for the t8code installation itself. Note that point 3 does not regard t8code at all, only libsc. Also I kept the subdirectories in my fix for point 1.

Concerning the `--with-sc` and `--with-p4est` flags: Yes, this is exactly what I had in mind; I overlooked that. My issue was just about being able to package libsc, p4est and t8code seperately (i.e. for some linux distro) without artificially removing files at the end.
Regarding the documentation, I guess something like 'Prevents additional installation of libsc/p4est, if already installed' would be more clear. Also I was slightly confused about what the 'path' to an installation of sc or p4est should be, before I become aware that you mean the installation prefix, but maybe thats just me.
Unfortunately there is another problem I noticed with these flags, because in the `SC_CHECK_INSTALL` macro in `sc/config/sc_package.m4` the paths to be checked are hardcoded as `<path>/etc`, `<path>/include`, etc.. This breaks if one chooses custom installation directories with the configure script.
A usual scenario would be the usage of `--sysconfdir=/etc` for FHS compliant file systems which have no `/usr/etc` directory. Since the FHS is followed by most Linux distributions, this is not exactly an edge case.
Note that this Problem also most likely has to be fixed only in libsc/p4est, not in t8code.

And to your question: Actually i work on HiFlow (https://emcl-gitlab.iwr.uni-heidelberg.de/hiflow3.org/hiflow3). I stumbled upon t8code while learning how p4est works, since we are using this for the mesh code.

**Comment by holke** [comment]
Thanks for the answer and for going the extra mile and posting 3 PRs - we welcome your contributions.
I am currently in a hurry, but will answer to your new points in the next days.
