### ISSUE TITLE
Refactor the hcube example

### ISSUE THREAD

**Issue by holke** [holke/t8code#181]
The basic hcube example should be reworked.

- It needs a better documentation
- Adaptation relies heavily on implementation details of the elements (i.e. type)
- It is way to much code for a basic example
- Do we even need two basic examples? One would be better.

**Comment by Davknapp** [comment]
Which of the high-level algorithms should be represented in the basic example? I think, that the creation of an initial refinement, an adaptive refinement step and an optional balancing and computation of the ghost layer should be enough. 

A nice adaptation criterion, that is independent of the element (except for vertices) can be the refinement of all elements that have an even coordinate with respect to the current level.

**Comment by holke** [comment]
Sounds good, i would say:

- Only one coarse mesh geometry. Maybe one for each dimension (maybe one command line parameter for dimension)
- Some Adaptation that is always triggered (no command line parameter)
- forest_partition (no command line parameter)
- balance (as optional via command line parameter)
