### ISSUE TITLE
Prism elements are missing an is_valid check

### ISSUE THREAD

**Issue by holke** [holke/t8code#218]
All element types should have an `t8_element_is_valid` check and assert in each function of `t8_default_X_cxx.cxx` whether the input elements are valid.
The prisms are missing this.

Are any other elements missing it?

**Comment by Davknapp** [comment]
I think the pyramids need it too. But that should be done on the pyramid-branch

**Comment by holke** [comment]
Yes, i adressed this in the pyramid PR.

**Comment by Davknapp** [comment]
Just checked upon that - prisms do have an is_valid check, see https://github.com/holke/t8code/blob/fea32fbf217418faa5d45804d2453e2139aafeda/src/t8_schemes/t8_default/t8_dprism_bits.c#L642

but it is only available in debug modus, in t8_default_prism_cxx.hxx the function is framed the `T8_ENABLE_DEBUG` - Makro

**Comment by Davknapp** [comment]
Ahh, now I understand what you meant. You are right, they are missing the check in the `t8_default_prism_cxx`-file
