### ISSUE TITLE
Docstring of `t8_forest_set_adapt` right?

### ISSUE THREAD

**Issue by sandro-elsweijer** [holke/t8code#251]
The docstring of `t8_forest_set_adapt` lists a `replace_fn` but the arguments accept no such function. This does not seem rigtht.
https://github.com/holke/t8code/blob/fb325d2d08e169860d241cbcaddd6ce382ed3bce/src/t8_forest.h#L229-L256

**Comment by Davknapp** [comment]
Solved in PR #253
