### ISSUE TITLE
Replace MPI_CHAR by MPI_BYTE

### ISSUE THREAD

**Issue by cburstedde** [holke/t8code#63]
If there are remaining occurrences of MPI_CHAR, it would make sense to convert them to MPI_BYTE.

There is one caveat in that sc_shmem will support MPI_BYTE only starting with upcoming develop/prev3-develop branches.

**Comment by holke** [comment]
Just checked the code.
There are zero occurences of MPI_CHAR in t8code itself, we are already using MPI_BYTE throughout.

Nevertheless, its a good reminder to keep in mind when doing parallel computation.
